services:
  - type: web
    name: carnet-adresses
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: carnet-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true

  - type: pserv
    name: carnet-db
    env: postgresql
    plan: free
    databaseName: addressbook
    databaseUser: carnet_user